#!/bin/sh
[ -z $1 ] && echo "isbn_to_bibtex needs a valid ISBN-ID as argument."
curl -s "http://api.crossref.org/works/${1}/transform/application/x-bibtex" -w "\\n"
# alternative format:
# curl -LH "Accept: text/bibliography; style=bibtex" "${1}" 
